### ISSUE TITLE
RangeError (end): Invalid value: Not in inclusive range 0..2: 3

### ISSUE THREAD

**Issue by fkranenburg** [shan-shaji/day_picker#7] opened 2022-02-12 18:35 UTC
I'm using the following list of `DayInWeek` but the widget does not allow these names.

```javascript
    List<DayInWeek> _days = [
      DayInWeek("Zo", isSelected: schedule.day1!),
      DayInWeek("Ma", isSelected: schedule.day2!),
      DayInWeek("Di", isSelected: schedule.day3!),
      DayInWeek("Wo", isSelected: schedule.day4!),
      DayInWeek("Do", isSelected: schedule.day5!),
      DayInWeek("Vr", isSelected: schedule.day6!),
      DayInWeek("Za", isSelected: schedule.day7!),
    ];
```

**Comment by shan-shaji** [comment] 2022-02-12 20:19
Hey @fkranenburg , Thank you for opening the issue. I have fixed the issue and will release a new version as soon as possible

**Comment by shan-shaji** [comment] 2022-02-12 20:25
Try using `day_picker: ^2.1.1`

**Comment by shan-shaji** [comment] 2022-02-13 11:37
@fkranenburg , Closing this issue for now. Hope the issue is fixed. If you are still facing the issue do reopen.

**Closed** 2022-02-13 11:37 UTC
